
SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

include Makefile.sub

RAYTRACER_O = $(O)raytracer.o $(O)vect.o $(O)color.o

all: $(A)water $(A)dali $(A)hello $(A)reflect $(A)plane

$(A)water: $(O)water.o $(RAYTRACER_O)
	$(LINK)

$(A)dali: $(O)dali.o $(RAYTRACER_O)
	$(LINK)

$(A)hello: $(O)hello.o $(RAYTRACER_O)
	$(LINK)

$(A)reflect: $(O)reflect.o $(RAYTRACER_O)
	$(LINK)

$(A)plane: $(O)plane.o $(RAYTRACER_O)
	$(LINK)

